# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4794714073465b962b72684e4e35f7fb89c327c860f3b2b88b9a59aeac0d952c9e04bbdf489e8838687eee484416e376a0d2ab260a3442be4ece39290f51c422

test:
  secret_key_base: 320874cd304d5298a898a04c24b7f8991de7d717b32e6fc6b934a311d34444524d8cf4cd56ddfb422dfc23f563735d936b8aba0fbc2245eaeca0fefc896b5b99

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
